version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_tienda
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: mi_tienda
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - tienda_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: admin123
    depends_on:
      - mysql
    networks:
      - tienda_net

volumes:
  mysql_data:

networks:
  tienda_net:
